### ISSUE TITLE
Really helpful to have a link to latest APK

### ISSUE THREAD

**Issue by cefn** [marcelogp/NoRefreshToggle#1]
I think I found the latest stable APK scrolling through the XDA-Developers forum link you provided, but it would be very useful indeed if you provided a link to it directly as I'm still not sure I found a build based on the latest code.

**Comment by marcelogp** [comment]
I keep the apk available at xda updated to the latest version here, so you can just use it.

**Comment by cefn** [comment]
I found two different versions in the thread I think. The first was the original I believe, as I initially had the package parsing problem. Could you provide detailed instructions how to find the 'apk available at xda' as without a URL and notion where in the thread to look it's pretty hard.

**Comment by cefn** [comment]
Sorry I think you mean that the link in the github project is a deeplink to the correct post in the thread.

I think therefore you mean I should use...
http://forum.xda-developers.com/attachment.php?attachmentid=1111768&d=1339026406
...which is the same as...
http://bit.ly/L7AlAq

**Comment by marcelogp** [comment]
The exact URL is at this github project description, which is:
http://forum.xda-developers.com/showpost.php?p=22800284&postcount=10

**Comment by marcelogp** [comment]
Exactly

**Comment by cefn** [comment]
I still get "There is a problem parsing the package" unfortunately. Maybe if I don't download it via the browser it could turn out better?

**Comment by marcelogp** [comment]
I don't think so. If you have access to adb, you can use "adb install NoRefreshToggle.apk" and see what is the cause of the error.

**Comment by shtrom** [comment]
Hey, I see your app is licensed unedr the GPL. You could push the latest version of the package to the FDroid OpenSource market [0]. This would make it easier to install and get update notifications.

I suppose the same holds for your other apps too (thanks for all of them, btw, they're quite good) (:

[0] http://f-droid.org/

**Comment by marcelogp** [comment]
Hi. Thanks for your comment. FDroid is quite nice, but since I'm developing exclusively for the Nook, I don't think my apps  would be suited for a public app repository.

**Comment by shtrom** [comment]
Well, I for one, as a Nook user, would like to be able to get them from there (:
